### ISSUE TITLE
Cerrar etiqueta i

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2019-francisco-luque-y-francisco-baca#1]
https://github.com/UCC-LabCompu2/proyectos2019-francisco-luque-y-francisco-baca/blob/783b0a22e28ace81fdce5386f0d690e3efe5ba2d/index.html#L62

**Comment by franluque2** [comment]
Solucionado, se cerro la etiqueta en index y en la pagina de la teoría.
