### ISSUE TITLE
Mejoren el estilo

### ISSUE THREAD

**Issue by edme88** [UCC-LabCompu2/proyectos2019-francisco-luque-y-francisco-baca#3]
Para el final:
Empleen alguna tipografía de google-fonts.
Empleen margin y padding para que el texto quede más centrado.

**Comment by edme88** [comment]
Y si pudieran usar pseudo clases para los links, sería genial!

**Comment by franluque2** [comment]
Se cambio un poco el estilo, no se si esta bien ahora.
